coins: [ethereum, bitcoin, solana, chainlink, ripple, tron]
horizons:
  intraday:
    lookback_days: 30
    granularity: 1h
  swing:
    lookback_days: 400   # ≈1.1 y
    granularity: 1d
indicators: [ema, sma, rsi, macd, bollinger, obv, atr, adx]
export:
  json: true
  csv: false
  sqlite: true
  charts: false
  individual_coin_files: false    # Only export aggregated files by default
output_dir: data/runs

# Enhanced data collection settings
market_data:
  collect_news: false             # CoinGecko Pro API does not provide reliable news headlines
  collect_metadata: true          # Fetch comprehensive coin metadata
  collect_categories: true        # Fetch sector/category data for rotation analysis
  collect_global: true           # Fetch global market data and dominance
  collect_tickers: true          # Fetch exchange/liquidity data (less frequent)
  collect_onchain: false         # Fetch onchain DEX data (advanced, may not be available)
  
  # News settings (disabled - CoinGecko API limitation)
  # news_limit: 20               # Number of news articles to fetch
  
  # Update frequencies (used by scheduling logic)
  update_frequencies:
    # news: "every_run"          # disabled - CoinGecko API limitation
    metadata: "daily"            # every_run, daily, weekly  
    categories: "every_run"      # every_run, daily, weekly
    global: "every_run"          # every_run, daily, weekly
    tickers: "weekly"            # every_run, daily, weekly
    onchain: "daily"             # every_run, daily, weekly